# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  g: $(gkey)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo $(g) | base64 -d > $PWD/key.json
    GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json go run main.go
    ls -la
    GOOGLE_APPLICATION_CREDENTIALS=$PWD/azure-credentials.json go run main.go
  displayName: 'Run a multi-line script'
