# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  g: $(gkey)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    azureSubscription: 'devops-id'
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world!!!!!!!!!!!!!!'
      GOOGLE_APPLICATION_CREDENTIALS=$PWD/azure-credentials.json go run main.go

- script: |
    echo $(g) | base64 -d > $PWD/key.json
    GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json go run main.go
    curl -v -H Metadata:true "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://iam.googleapis.com/projects/751286965207/locations/global/workloadIdentityPools/devops/providers/azure"
    
  displayName: 'Run a multi-line script'
